#! /bin/sh

#### BEGIN BSPWM MONITOR CONFIGURATION ####
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#### END BSPWM MONITOR CONFIGURATION ####

#### BEGIN BSPWM MAIN CONFIGRUATION ####
bspc config border_width                     2
bspc config window_gap                      10
bspc config top_padding                      0
bspc config bottom_padding                   0
bspc config left_padding                     0
bspc config right_padding         	     0
bspc config gapless_monocle       	  false
bspc config focus_follows_pointer         true
bspc config borderless_monocle    	  true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config split_ratio          0.50
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move
#### END BSPWM MAIN CONIFGURATION ####

#### BEGIN BSPWM COLOUR CONFIGURATION ####
bspc config normal_border_color               "#92aac7"
bspc config active_border_color	              "#1e1e1e"
bspc config focused_border_color	      "#74dcf0"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"
#### END BSPWM COLOUR CONFIGURATION ####

#### BEGIN BSPWM RULES ####
# To be added at a later time
#### END BSPWM RULES ####

#### BEGIN BSPWM AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
~/.fehbg &
udiskie &
flameshot &
xidlehook --not-when-fullscreen --not-when-audio --timer normal 300 slock &
~/.config/polybar/launch.sh &
xrdb -merge ~/.Xresources &
export MOZ_USE_XINPUT2=1 &
export QT_STYLE_OVERRIDE=adwaita-dark &
xscreensaver
#### END BSPWM AUTOSTART #####

